// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package todo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SyncParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncParams) Reset()         { *m = SyncParams{} }
func (m *SyncParams) String() string { return proto.CompactTextString(m) }
func (*SyncParams) ProtoMessage()    {}
func (*SyncParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0}
}

func (m *SyncParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncParams.Unmarshal(m, b)
}
func (m *SyncParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncParams.Marshal(b, m, deterministic)
}
func (m *SyncParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncParams.Merge(m, src)
}
func (m *SyncParams) XXX_Size() int {
	return xxx_messageInfo_SyncParams.Size(m)
}
func (m *SyncParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncParams.DiscardUnknown(m)
}

var xxx_messageInfo_SyncParams proto.InternalMessageInfo

// Item in list
type Item struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsDone               bool     `protobuf:"varint,2,opt,name=isDone,proto3" json:"isDone,omitempty"`
	Contents             string   `protobuf:"bytes,3,opt,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{1}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetIsDone() bool {
	if m != nil {
		return m.IsDone
	}
	return false
}

func (m *Item) GetContents() string {
	if m != nil {
		return m.Contents
	}
	return ""
}

type List struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *List) Reset()         { *m = List{} }
func (m *List) String() string { return proto.CompactTextString(m) }
func (*List) ProtoMessage()    {}
func (*List) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{2}
}

func (m *List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_List.Unmarshal(m, b)
}
func (m *List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_List.Marshal(b, m, deterministic)
}
func (m *List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_List.Merge(m, src)
}
func (m *List) XXX_Size() int {
	return xxx_messageInfo_List.Size(m)
}
func (m *List) XXX_DiscardUnknown() {
	xxx_messageInfo_List.DiscardUnknown(m)
}

var xxx_messageInfo_List proto.InternalMessageInfo

func (m *List) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

// The request message containing the user's name.
type ToggleRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToggleRequest) Reset()         { *m = ToggleRequest{} }
func (m *ToggleRequest) String() string { return proto.CompactTextString(m) }
func (*ToggleRequest) ProtoMessage()    {}
func (*ToggleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{3}
}

func (m *ToggleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToggleRequest.Unmarshal(m, b)
}
func (m *ToggleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToggleRequest.Marshal(b, m, deterministic)
}
func (m *ToggleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToggleRequest.Merge(m, src)
}
func (m *ToggleRequest) XXX_Size() int {
	return xxx_messageInfo_ToggleRequest.Size(m)
}
func (m *ToggleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ToggleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ToggleRequest proto.InternalMessageInfo

func (m *ToggleRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// The response message containing the greetings
type ToggleReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToggleReply) Reset()         { *m = ToggleReply{} }
func (m *ToggleReply) String() string { return proto.CompactTextString(m) }
func (*ToggleReply) ProtoMessage()    {}
func (*ToggleReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{4}
}

func (m *ToggleReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToggleReply.Unmarshal(m, b)
}
func (m *ToggleReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToggleReply.Marshal(b, m, deterministic)
}
func (m *ToggleReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToggleReply.Merge(m, src)
}
func (m *ToggleReply) XXX_Size() int {
	return xxx_messageInfo_ToggleReply.Size(m)
}
func (m *ToggleReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ToggleReply.DiscardUnknown(m)
}

var xxx_messageInfo_ToggleReply proto.InternalMessageInfo

func (m *ToggleReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SyncParams)(nil), "todo.SyncParams")
	proto.RegisterType((*Item)(nil), "todo.Item")
	proto.RegisterType((*List)(nil), "todo.List")
	proto.RegisterType((*ToggleRequest)(nil), "todo.ToggleRequest")
	proto.RegisterType((*ToggleReply)(nil), "todo.ToggleReply")
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_0e4b95d0c4e09639) }

var fileDescriptor_0e4b95d0c4e09639 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x4f, 0x4f, 0x84, 0x30,
	0x10, 0xc5, 0xb7, 0x2c, 0x22, 0x3b, 0xeb, 0xdf, 0x9a, 0x18, 0x82, 0x07, 0x49, 0x0f, 0xca, 0x89,
	0x18, 0xfc, 0x06, 0x1b, 0x0f, 0x6a, 0x3c, 0x90, 0x6a, 0xe2, 0x19, 0x61, 0xc4, 0x26, 0x85, 0x56,
	0x5a, 0xa3, 0x7c, 0x7b, 0x53, 0xd8, 0xd5, 0xec, 0xde, 0xde, 0x9b, 0x99, 0xcc, 0xfb, 0xcd, 0x00,
	0x58, 0x55, 0xab, 0x4c, 0xf7, 0xca, 0x2a, 0xea, 0x3b, 0xcd, 0x0e, 0x00, 0x9e, 0x87, 0xae, 0x2a,
	0xca, 0xbe, 0x6c, 0x0d, 0x7b, 0x04, 0xff, 0xc1, 0x62, 0x4b, 0x8f, 0xc0, 0x13, 0x75, 0x44, 0x12,
	0x92, 0xfa, 0xdc, 0x13, 0x35, 0x3d, 0x87, 0x40, 0x98, 0x3b, 0xd5, 0x61, 0xe4, 0x25, 0x24, 0x0d,
	0xf9, 0xda, 0xd1, 0x18, 0xc2, 0x4a, 0x75, 0x16, 0x3b, 0x6b, 0xa2, 0x79, 0x42, 0xd2, 0x05, 0xff,
	0xf3, 0x2c, 0x05, 0xff, 0x49, 0x18, 0x4b, 0x13, 0xd8, 0x13, 0x16, 0x5b, 0x13, 0x91, 0x64, 0x9e,
	0x2e, 0x73, 0xc8, 0x46, 0x06, 0x17, 0xc3, 0xa7, 0x06, 0xbb, 0x84, 0xc3, 0x17, 0xd5, 0x34, 0x12,
	0x39, 0x7e, 0x7e, 0xa1, 0xb1, 0xbb, 0xf1, 0xec, 0x1a, 0x96, 0x9b, 0x01, 0x2d, 0x07, 0x1a, 0xc1,
	0x7e, 0x8b, 0xc6, 0x94, 0x0d, 0x8e, 0x33, 0x0b, 0xbe, 0xb1, 0xf9, 0x3b, 0x84, 0x6e, 0xbb, 0x74,
	0xb9, 0x57, 0xe0, 0xbb, 0xcb, 0xe8, 0xc9, 0x14, 0xf8, 0x7f, 0x65, 0xbc, 0x46, 0x70, 0x74, 0x6c,
	0x46, 0x73, 0x08, 0xa6, 0xe5, 0xf4, 0x6c, 0xaa, 0x6f, 0xb1, 0xc4, 0xa7, 0xdb, 0x45, 0x2d, 0x07,
	0x36, 0x5b, 0xdd, 0xc0, 0x85, 0x50, 0x59, 0xd3, 0xeb, 0x2a, 0xc3, 0x9f, 0xb2, 0xd5, 0x12, 0x4d,
	0xf6, 0x81, 0x52, 0xaa, 0x6f, 0xd5, 0xcb, 0x7a, 0x75, 0x7c, 0xef, 0xf4, 0xab, 0xd3, 0x85, 0xfb,
	0x75, 0x41, 0xde, 0x82, 0xf1, 0xe9, 0xb7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x19, 0xf8,
	0x73, 0x82, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodolistClient is the client API for Todolist service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodolistClient interface {
	Sync(ctx context.Context, in *SyncParams, opts ...grpc.CallOption) (*List, error)
	Toggle(ctx context.Context, in *ToggleRequest, opts ...grpc.CallOption) (*ToggleReply, error)
}

type todolistClient struct {
	cc *grpc.ClientConn
}

func NewTodolistClient(cc *grpc.ClientConn) TodolistClient {
	return &todolistClient{cc}
}

func (c *todolistClient) Sync(ctx context.Context, in *SyncParams, opts ...grpc.CallOption) (*List, error) {
	out := new(List)
	err := c.cc.Invoke(ctx, "/todo.todolist/Sync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todolistClient) Toggle(ctx context.Context, in *ToggleRequest, opts ...grpc.CallOption) (*ToggleReply, error) {
	out := new(ToggleReply)
	err := c.cc.Invoke(ctx, "/todo.todolist/Toggle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodolistServer is the server API for Todolist service.
type TodolistServer interface {
	Sync(context.Context, *SyncParams) (*List, error)
	Toggle(context.Context, *ToggleRequest) (*ToggleReply, error)
}

func RegisterTodolistServer(s *grpc.Server, srv TodolistServer) {
	s.RegisterService(&_Todolist_serviceDesc, srv)
}

func _Todolist_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodolistServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.todolist/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodolistServer).Sync(ctx, req.(*SyncParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todolist_Toggle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodolistServer).Toggle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.todolist/Toggle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodolistServer).Toggle(ctx, req.(*ToggleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Todolist_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todo.todolist",
	HandlerType: (*TodolistServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _Todolist_Sync_Handler,
		},
		{
			MethodName: "Toggle",
			Handler:    _Todolist_Toggle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}
